# Build matrix / environment variable are explained on:
# http://about.travis-ci.org/docs/user/build-configuration/
# This file can be validated on:
# http://lint.travis-ci.org/

before_install: make -f travis/Makefile prepare_environment

os:
  - linux
  - osx

language: cpp
compiler:
  - gcc
  - clang

matrix:
  allow_failures:
    - os: osx

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "WG/iday4nudNJ9acP/gjjuXzI0Jw0MN0zP9JA3WueMvMV0UrVRnBKM+papB06XiB4Gyiaoy92pfOGzmby0ciMAvydBn2DyuGZhM1nXuEIbkQqfP3AR3z6nCZHY27NAhVnpnEAyb56FwD353JMVZj34cnRmcjgKArMM3Y8W66Zls="

addons:
  coverity_scan:
    project:
      name: "SimonKagstrom/kcov"
      description: "code coverage"
    notification_email: simon.kagstrom@gmail.com
    build_command_prepend: "mkdir -p coverity-build && cd coverity-build && cmake .. && cd .."
    build_command:   "travis/coverity-build.sh"
    branch_pattern: master

script: make -f travis/Makefile run-tests

notifications:
  recipients:
    - simon.kagstrom@gmail.com
  email:
    on_success: change
    on_failure: always

